name: Prevent Merge from Develop

on:
  pull_request:
  push:

jobs:
  check-merge-from-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pega histórico completo

      - name: Fetch develop branch
        run: |
          git fetch origin develop

      - name: Check for merge commits from develop
        run: |
          echo "🔎 Procurando por commits de merge onde 'develop' é um dos pais..."

          # Pega o SHA atual de develop
          DEVELOP_SHA=$(git rev-parse origin/develop)
          echo "👉 SHA atual de develop: $DEVELOP_SHA"

          # Varre todos os commits de merge na branch atual
          MERGE_COMMITS=$(git log origin/master..HEAD --merges --pretty=format:"%H")

          echo "👉 Commits de merge encontrados:"
          echo "$MERGE_COMMITS"

          for commit in $MERGE_COMMITS; do
            # Pega os dois pais do merge commit
            PARENTS=$(git log -1 --pretty=format:"%P" $commit)

            # Se um dos pais for develop, falha
            if echo "$PARENTS" | grep -q "$DEVELOP_SHA"; then
              echo "❌ ERRO: Encontrado merge de develop no commit $commit"
              exit 1
            fi
          done

          echo "✅ Nenhum merge de develop encontrado. Safe to proceed."
