on:
  push:
    branches:
      - master

jobs:
  reset-develop-to-master:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Reset develop to master when push's to master happens
        run: |
          git fetch
          git checkout develop
          git reset --hard origin/master
          git push origin develop --force